{% set name = "minizip" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zlib-ng/minizip-ng/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63e47a2b4dbac0da501f43f4da74f118dfb3ef0dee0ffbbe89428271002260f8

build:
  number: 4
  run_exports:
    - {{ pin_subpackage('minizip', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # [not win]
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config
  host:
    - bzip2
    - libiconv  # [not win]
    - openssl  # [not win]
    - xz 
    - zlib
    - zstd

test:
  commands:
    - test -f $PREFIX/lib/libminizip${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_LIB%\\libminizip.lib exit 1  # [win]

about:
  home: https://github.com/zlib-ng/minizip-ng
  # http://zlib.net/zlib_license.html
  license: Zlib
  license_family: Other
  license_file: LICENSE
  summary: minizip-ng is a zip manipulation library written in C.
  description: |
    minizip-ng is a zip manipulation library written in C
  dev_url: https://github.com/zlib-ng/minizip-ng

extra:
  recipe-maintainers:
    - akrherz
