{% set name = "minizip" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zlib-ng/minizip-ng/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: e39a736d4f55c22fa548e68225b2e92bc22aedd9ab90d002b0c5851e3a7bdace

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('minizip', max_pin='x') }}
  ignore_run_exports:
    - gtest

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # [not win]
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config
  host:
    - bzip2
    - libiconv  # [not win]
    - openssl  # [not win]
    - xz
    - zlib
    - zstd
    - gtest

test:
  commands:
    # presence of shared libraries
    - test -f $PREFIX/lib/libminizip${SHLIB_EXT}        # [unix]
    - if not exist %LIBRARY_BIN%\libminizip.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\libminizip.lib exit 1  # [win]

    # absence of static libraries
    - test ! -f $PREFIX/lib/libminizip.a                # [unix]

about:
  home: https://github.com/zlib-ng/minizicdp-ng
  license: Zlib
  license_family: Other
  license_file: LICENSE
  summary: minizip-ng is a zip manipulation library written in C.
  description: |
    minizip-ng is a zip manipulation library written in C
  dev_url: https://github.com/zlib-ng/minizip-ng

extra:
  recipe-maintainers:
    - akrherz
